#!/usr/bin/env python3
"""Generate the release manifest FROM EXECUTION.

The release manifest records:
  - the exact source commit (from git HEAD)
  - the sha256 and byte_length of every committed schema file
  - the sha256 and byte_length of every built package artifact (wheel + sdist),
    populated only when --build is supplied

The schema-digests section of the manifest is always generated from the
on-disk schema files; it is never hand-authored. The reference validator's
release-manifest-current check verifies those digests on every CI run.

Usage:
    python scripts/gen_release_manifest.py           # schema digests only
    python scripts/gen_release_manifest.py --build   # also build + hash artifacts
    python scripts/gen_release_manifest.py --check   # exit 1 if committed != fresh

The check in tests/test_contracts.py fails if the committed manifest is stale.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
COMMERCE_DIR = REPO_ROOT / "schemas" / "commerce" / "v0.1"
OUT = REPO_ROOT / "release" / "release-manifest.v0.2.0.json"
DIST_DIR = REPO_ROOT / "dist"


def _git_head() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except Exception as exc:
        return f"UNKNOWN:{exc}"


def _schema_digests() -> list[dict]:
    entries = []
    for schema_file in sorted(COMMERCE_DIR.glob("*.json")):
        raw = schema_file.read_bytes()
        doc = json.loads(raw)
        entries.append({
            "file": f"schemas/commerce/v0.1/{schema_file.name}",
            "id": doc.get("$id"),
            "title": doc.get("title"),
            "sha256": hashlib.sha256(raw).hexdigest(),
            "byte_length": len(raw),
        })
    return entries


def _artifact_digests() -> list[dict]:
    """Build the package and hash the artifacts. Requires the `build` package."""
    try:
        subprocess.run(
            [sys.executable, "-m", "build", "--outdir", str(DIST_DIR)],
            cwd=REPO_ROOT,
            check=True,
        )
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"Package build failed: {exc}") from exc

    entries = []
    for artifact in sorted(DIST_DIR.glob("dagr_commerce_contracts-*")):
        raw = artifact.read_bytes()
        entries.append({
            "file": str(artifact.relative_to(REPO_ROOT)),
            "sha256": hashlib.sha256(raw).hexdigest(),
            "byte_length": len(raw),
        })
    if not entries:
        raise SystemExit(f"No artifacts found in {DIST_DIR}")
    return entries


def build(include_artifacts: bool = False) -> dict:
    schema_digests = _schema_digests()
    manifest: dict = {
        "artifact": "dagr-commerce-contracts release manifest",
        "version": "0.2.0",
        "source_commit": _git_head(),
        "generated_at": datetime.datetime.now(datetime.timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        ),
        "note": (
            "Schema digests are computed from on-disk schema files at generation time "
            "and verified on every CI run by the release-manifest-current check. "
            "Package artifact digests are populated only when --build is supplied. "
            "This file is generated by scripts/gen_release_manifest.py, not hand-authored."
        ),
        "schemas": schema_digests,
        "package_artifacts": _artifact_digests() if include_artifacts else [],
    }
    return manifest


def render(manifest: dict) -> str:
    return json.dumps(manifest, indent=2) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--build",
        action="store_true",
        help="also build the package and record artifact digests",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if committed manifest schema-digests != fresh; ignores generated_at/source_commit/package_artifacts",
    )
    args = parser.parse_args(argv)

    fresh = build(include_artifacts=args.build)

    if args.check:
        if not OUT.exists():
            print("release manifest missing — run: python scripts/gen_release_manifest.py", flush=True)
            return 1
        committed = json.loads(OUT.read_text())
        if committed.get("schemas") != fresh["schemas"]:
            print(
                "release manifest schema-digests are stale — run: python scripts/gen_release_manifest.py",
                flush=True,
            )
            return 1
        print("release manifest schema-digests are current.")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(fresh))
    n = len(fresh["schemas"])
    na = len(fresh["package_artifacts"])
    print(f"wrote {OUT} ({n} schema digests, {na} artifact digest(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
