#!/usr/bin/env bash
# Re-vendor the ecosystem coordination JSON Schemas from a local
# arcs-ecosystem-kit checkout and regenerate schemas/ecosystem/PROVENANCE.yaml.
#
# This is a maintenance/regeneration aid, not part of CI. CI validates against
# the already-vendored copies so that a clean clone needs no external checkout.
#
# Usage: SRC=~/Developer/repos/arcs-ecosystem-kit scripts/vendor_ecosystem_schemas.sh
set -euo pipefail

SRC="${SRC:-$HOME/Developer/repos/arcs-ecosystem-kit}"
HERE="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$HERE/schemas/ecosystem"

if [ ! -d "$SRC/schemas" ]; then
  echo "arcs-ecosystem-kit schemas/ not found at $SRC" >&2
  exit 2
fi

mkdir -p "$OUT"
files="repository authority-references architecture-passport boundaries \
responsibilities capability-bindings contract-bindings dependencies lanes \
compatibility-projection conformance-projection exceptions release-state"

for f in $files; do
  cp "$SRC/schemas/ecosystem.$f.v0.1.schema.json" "$OUT/"
done

kit_commit="$(git -C "$SRC" rev-parse HEAD)"
kit_tree="$(git -C "$SRC" rev-parse 'HEAD^{tree}')"

{
  echo "# Provenance for vendored ecosystem coordination schemas."
  echo "# GENERATED by scripts/vendor_ecosystem_schemas.sh — do not hand-edit."
  echo "source_repository: \"thelaplage/arcs-ecosystem-kit\""
  echo "source_upstream_note: \"arcs-ecosystem-kit ecosystem coordination JSON Schemas (MIT); vendored verbatim so this repository validates its own .ecosystem/ declarations hermetically.\""
  echo "source_commit: \"$kit_commit\""
  echo "source_tree: \"$kit_tree\""
  echo "license: \"MIT (Vega Commons Project, Inc.); see NOTICE\""
  echo "retrieved_at: \"$(date -u +%Y-%m-%d)\""
  echo "schema_version: \"0.1\""
  echo "files:"
  for f in "$OUT"/*.json; do
    bn="$(basename "$f")"
    sha="$(shasum -a 256 "$f" | awk '{print $1}')"
    echo "  - path: \"schemas/ecosystem/$bn\""
    echo "    sha256: \"$sha\""
  done
} > "$OUT/PROVENANCE.yaml"

echo "Vendored 13 schemas and wrote $OUT/PROVENANCE.yaml"
